[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { git = "https://github.com/dymchenkko/risc0.git", branch = "feat/cargo-test"}

[package.metadata.risc0]
methods = ["guest"]
