[package]
name = "starter"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { git = "https://github.com/dymchenkko/risc0.git", branch = "feat/cargo-test"}
serde = "1.0"
